### ISSUE TITLE
Request for a more compatible way of defining "expressions"

### ISSUE THREAD

**Issue by HaoLi111** [mikldk/ryacas#13]
When we get a list of expressions in R,
e.g.
#ASSUMPTIONS
w<-expression(200+5*t)
p<-expression(0.65-0.01*t)
C<-expression(0.45*t)
R<-expression(p*w)
P<-expression(R-C)
#--------------------------------------------------------------
#Then ,we load symbolic calculation packages
library(Ryacas)
library(Deriv)
#Then subtitute and expand P(R,c) to get P(t)
yacas(P)##DO NOT RUN expression((0.65 - 0.01 * t) * (5 * t + 200) - 0.45 * t)
        ##There were 15 warnings (use warnings() to see them)
y<-yacas(P)
#The problem occurs here,
#because y is not an expression,
#Then we use
class(y)
#It shows [1] "yacas" and by clicking y in r studio we have`
![111](https://user-images.githubusercontent.com/32727671/34331760-97478968-e98e-11e7-8d7a-c31c2cbeedad.PNG)

#To get ready for the next step of calculations
y<-y[["text"]]
y<-parse(text=y)
#But an easier way of doing this, is
casOut<-function(y) return(parse(text=y[["text"]]))
y<-casOut(y)
The output expression need to be in the type of "expression" because it is the way R and also other R packages recognizes it. Also it prevents possible errors that might happen while copying the result manually.
However, simply naming it casOut() might not be a proper idea, as there are other types of output of yacas() that does not come in this format
for example when we get an expression solved,e.g.
dydt<-Deriv(y,"t")
Expand(dydt)
yacas("Solve((%)==0,t)")# shows the results properly
if i go,
t<-yacas("Solve((%)==0,t)")
It , not surprisingly, leads to an error, so if, for a function there is limited number of roots, is it possible that we assign t as a 'yacas' type that consist of a list with the text of expressions that can be later 'parse'd to expressions? 

I am aware that usually, in CAS, the roots of a function is a set or multiple sets of number. but if the output of the function solving the roots shows texts, it can be (maybe separarely) converted to an expression or a list of expressions. Because an expression can also be seen as a 'data'.

So what I am suggesting, if I go
t.opti<-yacas("Solve(a^2==2s),a")
t.opti#shows that
t.opti

#
#[[1]]text
#[1]sqrt(2 * s)
#[2]-sqrt(2 * s)
#[[2]]Variable
"a"#(Is it a better idea?)
#Then we can do something like
for(i in 1:length(t.opti[[1]])){
  assign(paste(t.opti[[2]][1],i),parse(t.opti[[1]][i]))
}
#It would be very convenient for the next step of the modelling (plotting, evaluating etc.) if these can be #written as functions to take place of the copy and paste process and the visible for loop, though I am
#not sure how this can be made concrete.
**_And , if in 'yacas' type, can we use a kind of 'transformation' funcitons to assign each 'text' line to expressions (&| functions so that they can be more easily used in R with other functions in math modelling? Huge thanks to developers._**

**Comment by ggrothendieck** [comment]
Please format this so that one can read it; however, if this is a problem with yacas as opposed to Ryacas then this is not the venue for that.

**Comment by HaoLi111** [comment]
As for the question, this is just to make the format fit in R better, as Ryacas is a powerful library, it would be great if the inputs and outputs have some "R accent" so that it fits seemlessly. I was writing some scripts for optimizations so came up with this.

**Comment by HaoLi111** [comment]
Consider using S3 to write an Rform for a normal yacas expression.
This will not work for all but if you take the derivatives of sum expr and then put them as r expression this might work.

Also simmilarly we can build some better translations from R to yacas as well.

These are some untilization functions (from the Utils.R in my repo). Please consider adding them to the new version.

```{r}
PrettyForm.function<-function(func){
  PrettyForm(as.expression(body(func)))
}

TeXForm.function<-function(func) TeXForm(as.expression(body(func)))

RForm<-function(y) UseMethod('RForm')
RForm.yacas<-function(y) return(parse(text=y[["text"]]))
```

**Comment by mikldk** [comment]
Thanks for this.

I just looked at your example. I agree that a better interface is needed. But wouldn't the following work for now?

```
w <- expression(200+5*t)
p <- expression(0.65-0.01*t)
C <- expression(0.45*t)
R <- expression(p*w)
P <- expression(R-C)

library(Ryacas)

y_body <- yacas(P)$text
y <- function(t) eval(y_body, list(t = t))
y(0)

dy_body <- yacas(paste0("D(t)", as.character(y_body)))$text
dy <- function(t) eval(dy_body, list(t = t))
dy(0)
```

Another approach using `Sym`:

```
ts <- Sym("t")
w <- 200+5*ts
p <- 0.65-0.01*ts
C <- 0.45*ts
R <- p*w
P <- R-C
P

y_body <- yacas(Simplify(P))$text
y <- function(t) eval(y_body, list(t = t))
y(0)

dy_body <- yacas(Simplify(paste0("D(t)", P)))$text
dy <- function(t) eval(dy_body, list(t = t))
dy(0)
```

**Comment by HaoLi111** [comment]
This is a good solution
