### ISSUE TITLE
Request for switches

### ISSUE THREAD

**Issue by HaoLi111** [mikldk/ryacas#14]
Hi I am just thinking of when defining/processing expressions it would be great of we can have a more intuitive way of viewing equations.
Is it possible to make something in the .GlobalEnv or in the yacas environment as a boolean value like
.PrettyForm<-TRUE #when it is turned on
so that when I type
---------------------------------------------------
>yacas(expression(x^2+y^2))
it automatically follows
> PrettyForm(yacas(expression(x^2+y^2)))#or arguably this function, PrettyForm()... not to be displayed

 2    2
x  + y 

>.PrettyForm<-FALSE#then it is turned off
---------------------------------------------------
or if we can define something like
---------------------------------------------------
switch_PrettyForm<-function(state = FALSE) ifelse(state = '',mget(.PrettyForm,pos = .Global.Env),.PrettyForm<<-state)#
---------------------------------------------------
Similarly when I run Ryacas there lots of warnings which arfe not needed nor relevant to the mathematical models I am applying,
but if I type
---------------------------------------------------
warnings('off')#
---------------------------------------------------
that doesn't work. 
I know someone does
---------------------------------------------------
suppressPackageStartupMessages(library(Ryacas))#when starting
---------------------------------------------------
at the start
Is there any switches that can be safely applied there?
Thanks. Looking for the 1.6.1 to be for R.

**Comment by mikldk** [comment]
Maybe we can have some `option`. I will try to look into it. Thanks for the suggestion.

**Comment by mikldk** [comment]
I have now tried making this for expressions.

You can try it out by enabling it:

```
Ryacas_options(prettyform_default = TRUE)
```

**Comment by HaoLi111** [comment]
Great. I am looking forward to the new update for which maybe I will write a new version of tutorial and write maybe example codes  email to some authors of math modelling books.

**Comment by HaoLi111** [comment]
> Ryacas_options(prettyform_default = TRUE)
Error in Ryacas_options(prettyform_default = TRUE) : 
  could not find function "Ryacas_options"

> options(prettyform_default = TRUE)
> x = Sym('x')
> (x+1)*(x-1)
expression((x + 1) * (x - 1))


why don't we just use print.expressions or print.Sym ?

**Comment by mikldk** [comment]
@HaoLi111 Did you install latest Github version? They should be there: <https://github.com/mikldk/ryacas/blob/master/R/options.R> and <https://github.com/mikldk/ryacas/blob/master/NAMESPACE#L95>.
