### ISSUE TITLE
PrettyForm output too narrow

### ISSUE THREAD

**Issue by HaoLi111** [mikldk/ryacas#17]
If I get a large equation in the environment:
...
then it is folding it to several parts which is inconvenient
 even the Rstudio default wideness is larger than this.
Could you not fold it?

/ 
| 
| 
| 
| 
| 
| 
\ 

                                                            
                             2 * pi * AR                    
------------------------------------------------------------
    /             2                                         
    | /  2 * AR  \                                          
    | | -------- |    /       2                         2 \ 
sqrt\ \ pi * ClA /  * \ 1 - Ma  + tan( sweep _ quarter )  / 
                                                            

          \
          |
--------- |
    \     |
    |     |
    |     |
+ 4 / + 2 |
          /

<OMOBJ>
  <OMS cd="logic1" name="true"/>
</OMOBJ>

But this folding is invisible from r
> a=PrettyForm.Func(ClA_correction_trapsimp)
> a

/ 
| 
| 
| 
| 
| 
| 
\ 

                                                            
                             2 * pi * AR                    
------------------------------------------------------------
    /             2                                         
    | /  2 * AR  \                                          
    | | -------- |    /       2                         2 \ 
sqrt\ \ pi * ClA /  * \ 1 - Ma  + tan( sweep _ quarter )  / 
                                                            

          \
          |
--------- |
    \     |
    |     |
    |     |
+ 4 / + 2 |
          /

<OMOBJ>
  <OMS cd="logic1" name="true"/>
</OMOBJ>

> str(a)
Classes 'Sym', 'character'  chr "( PrettyForm( {\n    2 * pi * AR/(2 + sqrt(4 + (AR/(ClA/2 * pi))^2 * ((1 - Ma^2) + tan(sweep_quarter)^2)))\n} ) )"

Thank you

**Comment by mikldk** [comment]
The output width can now be adjusted with the `set_output_width(n)` function. See also `get_output_width()`.
