### ISSUE TITLE
Old wiki as vignette

### ISSUE THREAD

**Issue by mikldk** [mikldk/ryacas#21]
Consider making old Google Code site available as one or more vignettes.

**Comment by grzegorzmazur** [comment]
I'm not sure if this is what you have in mind, but the old google code site has been (mostly) transformed  into http://grzegorzmazur.github.io/ryacas/

IRC, most of the things presented there is covered by vignettes, but it's been quite some time since, so I may be wrong

**Comment by mikldk** [comment]
Thanks, @grzegorzmazur . I agree that a good tutorial would be good. I will have a look at your page at some point and see if we can incorporate information from it somehow.
