### ISSUE TITLE
New tutorial proposal - Ryacas

### ISSUE THREAD

**Issue by HaoLi111** [mikldk/ryacas#26]
**_ZIP unavialiable temporarily as I am changing the list of contents. Sorry for this inconvenience. Please read the following info. Suggestions are welcomed. Thank you._**
@grzegorzmazur  @hojsgaard @mikldk 
#21 
I  will update this once every 3 days typically in this Month to get the main things   settled.

As is known to one who may concerns, Ryacas has no down-to-earth English tutorials to follow on R courses or YouTube or major blocks, which made it real difficult to have more users and contributors to better the project itself and explore wider applications with R itself.

The linkage of a CAS system and R can be cruicial to a lot of mathamatic modeling and statitistical pre-modeling and can possibly speed up the workflow of certain project or research. Ryacas provide so far the best (at least I think in terms of compatibility, reliability and power). 

A new tutorial would address the problem mentioned above and would be beneficial for both R and Yacas. Taking the advantage of the symbolic object convertion and expression derivations and evaluations more complexed modelling can be (OR HAVE BEEN) demonstrated.

**The tutorial MUST cover:**

 - Installation and quick explorations with base R and Ryacas.(done)
 - Yacas syntax and comparisions on different levels(I am horrible at this)
 - Different levels of Ryacas: yacmode(), yacas() and Sym() (most encouraged), usage, pros& cons, tips of avoiding nuissances(lol)
 - Examples: Ryacas in action - solve pure / applied math problems with code provided and discussed.(I have done some) (plenty of my previous codes to be organized)
 - Further development and deeper discussions of the parsing system. And tips to require() the package to do further tasks(well, this may offend some people though)

**IMPORTANT Main Structure to be discussed**

**Operating level to be discussed separately or together with CAS?**
**Main directions to develop, Exploratory calculation or part of modelling workflow?**

Discuss cases when a CAS is needed within a language environment

symbolic derivation for；
 -  eq solving
 - simplification
 - judging the state of a system

mixed computation when;
 - technical judgement in numerical computation is needed
 - computation modules needed as extension of n computing

**Questions:**

Who is also engaged and want to be one of the authors?

How should we licence the work? Creative Common? GNU FDL? R docu with(C)?

How should we share the work? Via Blogs? Gitbooks?

Should we make videos or prioritize on the tutorial?

12/19Update: I only found one existing Ryacas  Tutorial on Youtube and Yacas tutorials have been absent from major platforms.

**I would like to thank all of you for making it better.**

**Comment by HaoLi111** [comment]
You can reply here or through Email. Pls use lhrcplanes@qq.com instead of my gmail cuz I am in China. Sorry for the inconvenience.

**Comment by mikldk** [comment]
Thanks, @HaoLi111. I agree that a good tutorial would be good. I will have a look at your suggestion and get back.

**Comment by HaoLi111** [comment]
Progress:

Some materials is found. Some code written and some examples to be reused.

**_A better structure of tutorial is needed. The previous contents can be organized in different ways but so far I have not come up with a structure to avoid confusion or overlaps._**

**Comment by ggrothendieck** [comment]
The most important document is a lexicon to translate the old Ryacas to the new syntax.

**Comment by mikldk** [comment]
I think reading the "Getting started" vignette will explain everything well enough for `Ryacas0` users to use `Ryacas`.
