### ISSUE TITLE
Expression not R expression

### ISSUE THREAD

**Issue by mikldk** [mikldk/ryacas#28]
`eval()` vs `Eval()`. Maybe rename `expression(...)` from `yacas()` to `yacexpr()`.

**Comment by hojsgaard** [comment]
Med mindre der er en forskel mellem expr og expression?


========================================
Søren Højsgaard
Head of Department of Mathematical Sciences
Aalborg University, Denmark
Phone: +45 9940 8801

"Every saint has a past, every sinner has a future"
                                           Oscar Wilde
========================================
________________________________
Fra: Mikkel Meyer Andersen [notifications@github.com]
Sendt: 25. februar 2019 14:12
Til: mikldk/ryacas
Cc: Subscribed
Emne: [mikldk/ryacas] Expression not R expression (#28)


eval() vs Eval(). Maybe rename expression(...) from yacas() to yacexpr().

**Comment by mikldk** [comment]
Example:

```
> e <- yacas("x+2")
> e
expression(x + 2)
> str(e)
List of 2
 $ text  :  expression(x + 2)
 $ OMForm: chr "<OMOBJ>\n  <OMA>\n    <OMS cd=\"arith1\" name=\"plus\"/>\n    <OMV name=\"x\"/>\n    <OMI>2</OMI>\n  </OMA>\n</OMOBJ>\n"
 - attr(*, "class")= chr "yacas"
> str(e$text)
  expression(x + 2)
> 
> eval(e, list(x = 2))
expression(x + 2)
> eval(e$text, list(x = 2))
[1] 4
> 
> eval(expression(x + 2),  list(x = 2))
[1] 4
```

Problem is that `e` contains `expression` in `text`, but `text` is just printed in `print.yacas()`.

One option is to insert `cat("Yacas ")` in `print.yacas()` (L 38) and get:
```
> e
Yacas expression(x + 2)
```

Or `cat("yacexpr(", as.character(x[[1]]), ")\n", sep = "")` at L38 and get
```
> e
yacexpr(x + 2)
```

**Comment by mikldk** [comment]
Adressed by @a76898299baf72a985e69424f6014c774671def3.

**Comment by mikldk** [comment]
Now:
```
> e <- yacas("x+2")
> e
Yacas: x + 2
```

**Comment by mikldk** [comment]
Alternative:
```
> e <- yacas("x+2")
> e
yacas_expression(x + 2)
> Eval(e, list(x = 5))
[1] 7
```
