### ISSUE TITLE
JOSS Review Issues

### ISSUE THREAD

**Issue by MikeLydeamore** [mikldk/ryacas#32]
Thank you for your work on this software package and corresponding paper. CAS is somewhat out of my field of expertise (other than fairly basic use) but should the need arise I think this would make a useful addition to my workflow.

From a usability perspective, everything worked as described in the repository and the few tests I ran also went successfully. There are a couple of minor issues that I have identified:

- The repository is missing an OSI compatible license.
- The vignettes do not appear to be accessible from within R (and weren't listed by using `vigentte(pkg="ryacas")`. It's unclear to be whether they are supposed to be, but I think it would be a nice addition and in line with R package standards.
- There are currently no guidelines for contribution, reporting issues or seeking support.

Otherwise, I believe the package/paper is ready for publication.

**Comment by mikldk** [comment]
Thanks for your review and for helping making the package better by catching these shortages. I hope that commit 777cf33459d9b8349b1863149182c38652b4b23b have addressed your points.

**Comment by MikeLydeamore** [comment]
Thanks for that, looks like everything has been met from me.
