### ISSUE TITLE
Vignette explaining transition from Ryacas0 to Ryacas

### ISSUE THREAD

**Issue by mikldk** [mikldk/ryacas#33]
Mentioned in #26.

**Comment by ggrothendieck** [comment]
Also the README and Getting Started should not assume any knowledge of yacas itself and should show how to create a yacas variable in R and work with that.  

How do you do this in Ryacas (code works in Ryacas0) which I would regard as the preferred style. 

```
x <- Sym("x")
x * x
```

**Comment by mikldk** [comment]
It's now called `yac_symbol()`. Thanks for the suggestion. I'll be happy to consider a PR.

**Comment by ggrothendieck** [comment]
That is an overly verbose name in my opinion.  `Sym` was better.

**Comment by HaoLi111** [comment]
In this case maybe yacas::Sym(...) is already sufficient to specify which package the function comes from I think. Maybe use soft deprecation if you really want to rename it?

**Comment by mikldk** [comment]
Thanks for your comments. I'll think more about how to handle this. I agree the interface can be improved, but I also think an alias will do much, e.g. `ysym()` or `sym()`.

**Comment by ggrothendieck** [comment]
I see no reason to rename it. Sym is best. sym is used by dpyr. yac_sym and ysym don't add anything but useless verbosity.

**Comment by mikldk** [comment]
I think reading the "Getting started" vignette will explain everything well enough for `Ryacas0` users to use `Ryacas`.
